// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inf.proto

package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enum type default is int32
type Ua int32

const (
	Ua_Unkown  Ua = 0
	Ua_Web     Ua = 1
	Ua_H5      Ua = 2
	Ua_Ios     Ua = 3
	Ua_Android Ua = 4
	Ua_Pc      Ua = 5
	Ua_Wx      Ua = 6
)

var Ua_name = map[int32]string{
	0: "Unkown",
	1: "Web",
	2: "H5",
	3: "Ios",
	4: "Android",
	5: "Pc",
	6: "Wx",
}
var Ua_value = map[string]int32{
	"Unkown":  0,
	"Web":     1,
	"H5":      2,
	"Ios":     3,
	"Android": 4,
	"Pc":      5,
	"Wx":      6,
}

func (x Ua) String() string {
	return proto.EnumName(Ua_name, int32(x))
}
func (Ua) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_inf_8df23074f44805ff, []int{0}
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ua                   int32    `protobuf:"varint,2,opt,name=ua" json:"ua,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_inf_8df23074f44805ff, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetUa() int32 {
	if m != nil {
		return m.Ua
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_inf_8df23074f44805ff, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// error ua
type ErrorUa struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorUa) Reset()         { *m = ErrorUa{} }
func (m *ErrorUa) String() string { return proto.CompactTextString(m) }
func (*ErrorUa) ProtoMessage()    {}
func (*ErrorUa) Descriptor() ([]byte, []int) {
	return fileDescriptor_inf_8df23074f44805ff, []int{2}
}
func (m *ErrorUa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorUa.Unmarshal(m, b)
}
func (m *ErrorUa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorUa.Marshal(b, m, deterministic)
}
func (dst *ErrorUa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorUa.Merge(dst, src)
}
func (m *ErrorUa) XXX_Size() int {
	return xxx_messageInfo_ErrorUa.Size(m)
}
func (m *ErrorUa) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorUa.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorUa proto.InternalMessageInfo

func (m *ErrorUa) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrorUa) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ErrorUa)(nil), "helloworld.ErrorUa")
	proto.RegisterEnum("helloworld.Ua", Ua_name, Ua_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inf.proto",
}

func init() { proto.RegisterFile("inf.proto", fileDescriptor_inf_8df23074f44805ff) }

var fileDescriptor_inf_8df23074f44805ff = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0xdb, 0x36, 0x6b, 0x47, 0x91, 0x65, 0x0e, 0x12, 0x3c, 0x95, 0x9c, 0x8a, 0x87,
	0x1c, 0x2a, 0x22, 0x78, 0x10, 0x3c, 0x48, 0xdb, 0x9b, 0x44, 0x42, 0xcf, 0xdb, 0x66, 0xd4, 0xe2,
	0x76, 0x27, 0x6e, 0x12, 0x6a, 0xfe, 0xbd, 0x6c, 0x68, 0x6d, 0x05, 0x4f, 0xfb, 0xde, 0x7e, 0xbc,
	0x07, 0xf3, 0x60, 0xb4, 0x71, 0x6f, 0x69, 0xe9, 0xb9, 0x66, 0x84, 0x0f, 0xb2, 0x96, 0x77, 0xec,
	0x6d, 0x91, 0x4c, 0xe1, 0x62, 0x1e, 0x5c, 0x46, 0x5f, 0x0d, 0x55, 0x35, 0x22, 0x0c, 0x9c, 0xd9,
	0x52, 0x2c, 0xc6, 0x62, 0x32, 0xca, 0x3a, 0x8d, 0x97, 0x20, 0x1b, 0x13, 0xcb, 0xb1, 0x98, 0x0c,
	0x33, 0xd9, 0x98, 0xe4, 0x01, 0x60, 0x9f, 0x29, 0x6d, 0x8b, 0x31, 0xa8, 0x2d, 0x55, 0x95, 0x79,
	0x3f, 0x84, 0x0e, 0x36, 0x74, 0xad, 0xb9, 0xa0, 0x7d, 0xb2, 0xd3, 0xc9, 0x3d, 0xa8, 0x67, 0xef,
	0xd9, 0xe7, 0xe6, 0x17, 0x8b, 0x23, 0x3e, 0x2d, 0x93, 0x7f, 0xca, 0x6e, 0x66, 0x20, 0x73, 0x83,
	0x00, 0x51, 0xee, 0x3e, 0x79, 0xe7, 0x74, 0x0f, 0x15, 0xf4, 0x97, 0xb4, 0xd2, 0x02, 0x23, 0x90,
	0xf3, 0x3b, 0x2d, 0xc3, 0xc7, 0x82, 0x2b, 0xdd, 0xc7, 0x73, 0x50, 0x4f, 0xae, 0xf0, 0xbc, 0x29,
	0xf4, 0x20, 0xd0, 0x97, 0xb5, 0x1e, 0x86, 0x77, 0xf9, 0xad, 0xa3, 0xe9, 0x02, 0xd4, 0xcc, 0x13,
	0xd5, 0xe4, 0xf1, 0x11, 0xce, 0x5e, 0x4d, 0xdb, 0xdd, 0x82, 0x71, 0x7a, 0x5c, 0x25, 0x3d, 0x9d,
	0xe4, 0xfa, 0xea, 0x1f, 0x52, 0xda, 0x36, 0xe9, 0xad, 0xa2, 0x6e, 0xcf, 0xdb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x43, 0x6a, 0xc7, 0x7a, 0x5c, 0x01, 0x00, 0x00,
}
